### ISSUE TITLE
在近期更新以后，无法自动启动雷电模拟器

### ISSUE THREAD

**Issue by jiangyh91** [pur1fying/blue_archive_auto_script#147]
之前一直能正常使用，在近期的某一次更新以后，如果尝试使用自动启动功能，输出以下错误信息
    INFO | 2024-09-08 12:36:31 | --------Initializing All Data---------- 
    INFO | 2024-09-08 12:36:31 | --------------Init Emulator---------------- 
    INFO | 2024-09-08 12:36:31 | -- BAAS Check Emulator Start -- 
 WARNING | 2024-09-08 12:36:32 | -- Emulator Process dnplayer.exe is not running, start Emulator -- 
   ERROR | 2024-09-08 12:36:32 | can only concatenate list (not "NoneType") to list 
   ERROR | 2024-09-08 12:36:32 | Emulator start failed 
CRITICAL | 2024-09-08 12:36:32 | Initialization Failed

**Comment by pur1fying** [comment]
模拟器路径的配置？

**Comment by jiangyh91** [comment]
我设置的是雷电模拟器的启动exe(dnplayer.exe)，在更新以后没有修改过。 C:/Games/leidian/LDPlayer9/dnplayer.exe

**Comment by pur1fying** [comment]
@RedDeadDepresso Hello, I found the exception is caused by this function which you committed at d6976a9cc0d0c9bdd48a3f48d7a3433b5baef21f
![image](https://github.com/user-attachments/assets/da671e3e-ba70-4b94-a2c7-a5a882c88264)

it seems it is expected to return a list of string instead of None so I revised it to  

![image](https://github.com/user-attachments/assets/b0820876-57a8-4ab8-a514-52e295302dd6)

and it functions correctly.

**Comment by jiangyh91** [comment]
感谢修复，已经可以正常使用了
